### ISSUE TITLE
git 问题解决

### ISSUE THREAD

**Issue by cuihuacuihua** [wangzilinn/Chuying_guide#1]
lenovo@DESKTOP-HA5DF50 MINGW64 ~/learning (master)
$ git commit -m "test"

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <1364555943@qq.com>) not allowed

出现这个问题，ident anme not allowed,缺少邮箱所对应的用户，所以只需要把用户名补上
 git config --global user.name "******"
不需要多加就会有
lenovo@DESKTOP-HA5DF50 MINGW64 ~/learning (master)
$ git commit -m "test"
[master (root-commit) 64cb56d] test
 1 file changed, 3 insertions(+)
 create mode 100644 read.txt

**Comment by wangzilinn** [comment]
已添加
