### ISSUE TITLE
程序调用问题及下载

### ISSUE THREAD

**Issue by cuihuacuihua** [wangzilinn/Chuying_guide#3]
（1）例如  void display()......
程序调用时依旧为 void display();
问题，程序未被调用。
解决，不加void ,应该为display();
（2）在主函数中更改输出口（舵机），但是下载程序后仍旧是只在原来的口检测到信号；
问题，此主程序非彼主程序，主程序可能未打开，修改的只是未添加的程序；
解决，任务窗口打开程序，再次修改。

**Comment by wangzilinn** [comment]
已添加
